### ISSUE TITLE
M1 Professional Development Review

### ISSUE THREAD

**Issue by kaylagordon** [turingschool/curriculum-site#47]
Go through the M1 PD pages on the curriculum site and ensure that:
1. Staff has access to view/edit all forms that are linked (exit tickets, surveys, etc)
2. Ensure all live lessons are added to the M1 calendar
3. Either click through mods 2-4 to check their links OR make a card in `icebox` for checking those links/forms access.

**Comment by hfaerber** [comment]
@juliet-e 
- [ ] Monday of Week 3 has a PD session called Intro to Storytelling on the calendar currently.  I'm not sure if that session is staying or being replaced.  If it is staying, we should make a copy of the slide deck in the SE1 PD folder on the G:drive.  I haven't had a chance to dig for where that slide deck lives.
I have already made a copy of the Jamboard and updated that link on the calendar.
Note:  On the calendar, once I ensure the link is correct I add a `*` after the link.  Once I ensure the whole event has the correct links, I add a `*` after the event title.   If a non-pd lesson had a slide deck attached, I copied the slide deck into the SE1 Lesson Resources folder on the G:drive and then add `**` to the calendar event (with no link to the slide since they haven't been updated and might not be used.  We will have to update and add the link as part of our lesson prep if we plan to use slides.)

**Comment by juliet-e** [comment]
Storytelling Exit Ticket: https://forms.gle/wgn1MyVucQZkgzzdA
Door 2 Exit Ticket: https://forms.gle/1WaG8tXtWKm4DL2r5
links updated in slides, just leaving here for calendar links if there are any

**Comment by hfaerber** [comment]
Calendar has been updated accordingly ✅
