### ISSUE TITLE
Request Testing in Rails

### ISSUE THREAD

**Issue by memcmahon** [turingschool/curriculum-site#95]
Existing Lesson - https://backend.turing.edu/module2/lessons/feature_testing_2

- [x] Add to curriculum site
- [x] Review for potential updates

**Note**
This issue is related to #93 #94 #96.  These lessons should create/build on the [Set List](https://github.com/turingschool-examples/set-list-7) application

--- 
7/12 Update -- This will now be Request Testing in Rails
- [x] Build off of current lesson to introduce the idea of integration testing but no need to introduce capybara
- [ ] Add branch(es) to new API set list (#166 )  application for practice - https://github.com/turingschool-examples/set-list-api (branch songs-index-complete could be a good starting point to build off of, as it has one endpoint, and lesson could demo how to write a test for that endopint, and then students could write a test for a show endpoint for a single song)

**Comment by juliet-e** [comment]
At this point, students will not know about one-to-many relationships, so we should just make sure this lesson doesn't use resources that have foreign keys/db relationships yet

ALSO, in order to allow Capybara to detect DOM changes, JS files need to be compiled with the test so we need to add the selenium webdriver gem to our Rails apps, and then add the `js: true` parameter when defining our test i.e. `RSpec.describe . . . type: :feature, js: true do`

We should teach students that if they have any JS dom manipulations on the page, they'll need this setup
